<a href="https://colab.research.google.com/github/abihaittfaq-create/DREAM-HOME-Real-Estate-Property-platform/blob/main/Real_Estate_AI_Lead_Scoring_inquiry_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import json

In [1]:
from google.colab import files

uploaded = files.upload()

Saving inquiries (1).json to inquiries (1).json

In [3]:
with open("inquiries (1).json", "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

df.head()

,inquiryId,propertyId,budget,location,timeline,message
0,I001,P052,177486,Karachi,Within 1 month,I am ready to buy and would like a viewing.
1,I002,P030,304864,Islamabad,Just browsing,Need more details before making a decision.
2,I003,P077,145423,Islamabad,Within 1 month,Need more details before making a decision.
3,I004,P067,293340,Faisalabad,6 months,I am ready to buy and would like a viewing.
4,I005,P070,384442,Lahore,Within 1 month,Just exploring options.

In [ ]:
print(df.info())
print(df.head())

In [4]:
def get_intent(message):

    message = message.lower()

    if "ready to buy" in message:
        return "Buying Intent"

    elif "need more details" in message:
        return "Information Request"

    elif "contact me" in message:
        return "Contact Request"

    elif "exploring options" in message:
        return "Browsing"

    else:
        return "Other"

In [5]:
df["Intent"] = df["message"].apply(get_intent)

df[["message","Intent"]].head(10)

                                       message               Intent
0  I am ready to buy and would like a viewing.        Buying Intent
1  Need more details before making a decision.  Information Request
2  Need more details before making a decision.  Information Request
3  I am ready to buy and would like a viewing.        Buying Intent
4                      Just exploring options.             Browsing
5                      Just exploring options.             Browsing
6  I am ready to buy and would like a viewing.        Buying Intent
7  I am ready to buy and would like a viewing.        Buying Intent
8   Please contact me regarding this property.      Contact Request
9  I am ready to buy and would like a viewing.        Buying Intent

In [6]:
def lead_score(row):

    score = 0

    # Timeline Score
    if row["timeline"] == "Within 1 month":
        score += 40

    elif row["timeline"] == "Within 3 months":
        score += 25

    elif row["timeline"] == "6 months":
        score += 15

    else:
        score += 5

    # Intent Score
    if row["Intent"] == "Buying Intent":
        score += 40

    elif row["Intent"] == "Contact Request":
        score += 30

    elif row["Intent"] == "Information Request":
        score += 20

    elif row["Intent"] == "Browsing":
        score += 10

    return score

In [ ]:
df["Lead Score"] = df.apply(lead_score, axis=1)

df.head()

In [7]:
def lead_category(score):

    if score >= 70:
        return "Hot Lead"

    elif score >= 40:
        return "Warm Lead"

    else:
        return "Cold Lead"

In [ ]:
df["Lead Category"] = df["Lead Score"].apply(lead_category)

df.head(20)

In [ ]:
df[["inquiryId",
    "message",
    "Intent",
    "timeline",
    "Lead Score",
    "Lead Category"]]

In [8]:
df.to_csv("Lead_Scoring_Output.csv", index=False)

print("Done!")

Done!

In [10]:
# User Input Testing

user_message = input("Enter your inquiry: ")

# Intent Recognition
user_intent = get_intent(user_message)

# User details
user_budget = int(input("Enter your budget: "))
user_timeline = input("Enter your timeline: ")
user_location = input("Enter your location: ")


# Create user data
user_data = {
    "message": user_message,
    "budget": user_budget,
    "timeline": user_timeline,
    "location": user_location,
    "Intent": user_intent
}


# Lead Score
user_score = lead_score(user_data)

# Lead Category
user_category = lead_category(user_score)


# Final Result
print("\n--- Lead Analysis ---")
print("Message:", user_message)
print("Intent:", user_intent)
print("Lead Score:", user_score)
print("Lead Category:", user_category)

Enter your inquiry: i want to buy a house
Enter your budget: 6064
Enter your timeline: one day
Enter your location: karachi

--- Lead Analysis ---
Message: i want to buy a house
Intent: Other
Lead Score: 5
Lead Category: Cold Lead